<a href="https://colab.research.google.com/github/Deepanshu-Paul/Customer_Churn_Prediction/blob/main/RNN_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.text import Tokenizer

sent = [
    "Cat purrs on windowsill.",
    "Children splash in puddles.",
    "Sailboat glides on lake.",
    "Bread smells warm, tempting.",
    "Sunset paints sky vibrant."
]

voc_size = 10000

# Create a tokenizer and fit it on the sentences
tokenizer = Tokenizer(num_words=voc_size, oov_token='<OOV>')
tokenizer.fit_on_texts(sent)

# Get the word index for each sentence
sequences = tokenizer.texts_to_sequences(sent)

# One-hot encode the sequences
onehot = [to_categorical(word_index, num_classes=voc_size) for sequence in sequences for word_index in sequence]

print(sequences)

[[3, 4, 2, 5], [6, 7, 8, 9], [10, 11, 2, 12], [13, 14, 15, 16], [17, 18, 19, 20]]


In [4]:
## Word Embedding

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [5]:
import numpy as np
import pandas as pd

In [6]:
sent_length = 8
embedded_docs = pad_sequences(sequences, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[ 0  0  0  0  3  4  2  5]
 [ 0  0  0  0  6  7  8  9]
 [ 0  0  0  0 10 11  2 12]
 [ 0  0  0  0 13 14 15 16]
 [ 0  0  0  0 17 18 19 20]]


In [13]:
## feature representation
dim = 10
voc_size = 10000

In [16]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

In [17]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [18]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 248ms/step


array([[[ 7.8294650e-03,  1.5080277e-02,  2.1624390e-02,  5.7041645e-03,
          2.3313228e-02, -9.0139024e-03, -9.4078183e-03, -6.6523068e-03,
          3.6927667e-02, -4.0283561e-02],
        [ 7.8294650e-03,  1.5080277e-02,  2.1624390e-02,  5.7041645e-03,
          2.3313228e-02, -9.0139024e-03, -9.4078183e-03, -6.6523068e-03,
          3.6927667e-02, -4.0283561e-02],
        [ 7.8294650e-03,  1.5080277e-02,  2.1624390e-02,  5.7041645e-03,
          2.3313228e-02, -9.0139024e-03, -9.4078183e-03, -6.6523068e-03,
          3.6927667e-02, -4.0283561e-02],
        [ 7.8294650e-03,  1.5080277e-02,  2.1624390e-02,  5.7041645e-03,
          2.3313228e-02, -9.0139024e-03, -9.4078183e-03, -6.6523068e-03,
          3.6927667e-02, -4.0283561e-02],
        [ 3.1434409e-03, -2.9738856e-02, -1.6275227e-02, -2.7113069e-02,
         -1.1366915e-02, -3.4661055e-02, -5.6765079e-03, -4.5722511e-02,
          2.6022878e-02,  2.6905131e-02],
        [-4.6930816e-02,  2.9446010e-02, -4.7580816e-02,  1.

In [21]:
model.predict(embedded_docs[0].reshape(1, -1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step


array([[[ 0.00782946,  0.01508028,  0.02162439,  0.00570416,
          0.02331323, -0.0090139 , -0.00940782, -0.00665231,
          0.03692767, -0.04028356],
        [ 0.00782946,  0.01508028,  0.02162439,  0.00570416,
          0.02331323, -0.0090139 , -0.00940782, -0.00665231,
          0.03692767, -0.04028356],
        [ 0.00782946,  0.01508028,  0.02162439,  0.00570416,
          0.02331323, -0.0090139 , -0.00940782, -0.00665231,
          0.03692767, -0.04028356],
        [ 0.00782946,  0.01508028,  0.02162439,  0.00570416,
          0.02331323, -0.0090139 , -0.00940782, -0.00665231,
          0.03692767, -0.04028356],
        [ 0.00314344, -0.02973886, -0.01627523, -0.02711307,
         -0.01136691, -0.03466105, -0.00567651, -0.04572251,
          0.02602288,  0.02690513],
        [-0.04693082,  0.02944601, -0.04758082,  0.01633743,
         -0.02472483, -0.018619  , -0.00924058,  0.03955234,
          0.0071189 , -0.01331646],
        [-0.00512202, -0.00252289,  0.03350805, -0.0

<div class="markdown-google-sans">

<a name="machine-learning-examples"></a>

### Featured examples

</div>

- [Retraining an Image Classifier](https://tensorflow.org/hub/tutorials/tf2_image_retraining): Build a Keras model on top of a pre-trained image classifier to distinguish flowers.
- [Text Classification](https://tensorflow.org/hub/tutorials/tf2_text_classification): Classify IMDB movie reviews as either *positive* or *negative*.
- [Style Transfer](https://tensorflow.org/hub/tutorials/tf2_arbitrary_image_stylization): Use deep learning to transfer style between images.
- [Multilingual Universal Sentence Encoder Q&A](https://tensorflow.org/hub/tutorials/retrieval_with_tf_hub_universal_encoder_qa): Use a machine learning model to answer questions from the SQuAD dataset.
- [Video Interpolation](https://tensorflow.org/hub/tutorials/tweening_conv3d): Predict what happened in a video between the first and the last frame.
